name: 
on:
    workflow_dispatch:
jobs:
    scheduled:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/setup-go@v4
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Get deps
        run: go install github.com/ericchiang/pup@latest
      - name: Fetch and parse latest data
        run: |-
          curl -s "https://library.vcvrack.com/questionablemodules" | pup ':contains("Popularity: ") text{}' | sed -r 's/ Popularity: //g' | tr -d " \t\n\r" > popularity
          pop=$(cat popularity)
          sed -i "s/Library\/[0-9]*,[0-9]*\/blue/Library\/$pop\/blue/g" README.md
      - name: Commit and push if the data has changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push